### ISSUE TITLE
Obsolete cookie encryption configuration?

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#1071]
@pellaea 
Can I remove this from `config/application.rb`:
```ruby
    # Still validating 5.2 deploy and want to allow rollback
    # TODO: Remove this once we are satisfied with 5.2 deplay.
    config.action_dispatch.use_authenticated_cookie_encryption = false
```

**Comment by pellaea** [comment]
Haha!  I think it's fair to say that we are "satisfied with 5.2 deploy"! :)

**Comment by JoeCohen** [comment]
Thanks! I'll do a PR. 
(Is it likely to cause temporary disruption of sessions when it's deployed?)

**Comment by pellaea** [comment]
Yeah, I imagine so.  People will have to remember their login again.  I bet
there will be lots of new password emails to hotmail that get lost.  Sigh.

**Comment by JoeCohen** [comment]
I'm thinking about deploying this evening; I'll be able to help with lost logins tonight and early tomorrow. Then probably out of commission until Tues eve or Weds a.m.

**Comment by pellaea** [comment]
That'll be fine.  Thanks for the heads up, Joe!

**Comment by JoeCohen** [comment]
I merged and deployed this.
I was logged in at the time and was able to continue without being logged out.

**Comment by pellaea** [comment]
Great news!  Thanks, Joe.

**Comment by JoeCohen** [comment]
I'll add something to the banner now.
