### ISSUE TITLE
Proposed Name bugs from Django Grootmyers

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#1134]
This will further document 2 (related?) bugs that are happening to Django Grootmyers. 
The bugs surfaced in a [Facebook post](https://www.facebook.com/groups/mushroomobserver/permalink/1476118272849117/) and were mentioned by @AlanRockefeller in [Slack](https://mushroomobserver.slack.com/archives/C040TH9FV/p1661355403166529). 
- The bugs both relate to Proposed Names.
- They do not happen for all Observations or Proposed Names.
- It doesn't appear to be a browser issue, as Django has tried several browsers, all with the same result.
- I have been unable to replicate the bugs when logged in as me. (@AlanRockefeller also cannot replicate.)
- I can, however, replicate the bugs in the live db by switching to Admin Mode, then Switching Users to `heelsplitter`. 
But that procedure does not succeed in replicating the bug in the dev environment.

To replicate. 
Bug 1: Cannot propose a Name for certain Observations.
- Login to the website
- Switch to Admin Mode
- Switch Users to `heelsplitter`
- Goto https://mushroomobserver.org/335734 (This a Pulk observation.)
- click Propose Another Name
- Enter a valid scientific name, e.g. `Collybiopsis`
- click Create
Result: "The page you were looking for doesn't exist."

<img width="560" alt="Screen Shot 2022-08-29 at 1 11 28 PM" src="https://user-images.githubusercontent.com/45460/187289546-df49f3da-e1e8-4d91-91f8-db2833f710d5.png">

Production Log entry:
```ruby
I, [2022-08-29T18:18:15.127852 #1418701]  INFO -- : Started GET "/335734" for 50.45.202.103 at 2022-08-29 18:18:15 +0000
I, [2022-08-29T18:18:15.129487 #1418701]  INFO -- :   Parameters: {"id"=>"335734"}
W, [2022-08-29T18:18:17.028217 #1418701]  WARN -- : TIME: 1.898577175 200 observations show user 50.45.202.103  https://mushroomobserver.org/335734     Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
I, [2022-08-29T18:18:56.456748 #1418701]  INFO -- : Started GET "/naming/create/335734" for 50.45.202.103 at 2022-08-29 18:18:56 +0000
I, [2022-08-29T18:18:56.458719 #1418701]  INFO -- :   Parameters: {"id"=>"335734"}
W, [2022-08-29T18:18:57.429095 #1418701]  WARN -- : TIME: 0.970195495 200 naming create user 50.45.202.103      https://mushroomobserver.org/naming/create/335734       Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
I, [2022-08-29T18:19:48.792335 #1418701]  INFO -- : Started POST "/naming/create/335734?approved_name=" for 50.45.202.103 at 2022-08-29 18:19:48 +0000
I, [2022-08-29T18:19:48.794639 #1418701]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"lI6NLVpwmF9h8wSvLbatIeO9t2GuNTLyQB8ipN/65DXCKtz3NQLdfuYXyq3qCoxqXdQDQnhL91yv7okKGZSv/g==", "commit"=>"Create", "name"=>{"name"=>"Collybiopsis "}, "vote"=>{"value"=>"1.0"}, "reason"=>{"1"=>{"check"=>"1", "notes"=>"Test to see if I can replicate error"}, "2"=>{"check"=>"0", "notes"=>""}, "3"=>{"check"=>"0", "notes"=>""}, "4"=>{"check"=>"0", "notes"=>""}}, "was_js_on"=>"yes", "approved_name"=>"", "id"=>"335734"}
I, [2022-08-29T18:19:54.045235 #1418701]  INFO -- : Redirected to https://mushroomobserver.org/335734
W, [2022-08-29T18:19:54.045703 #1418701]  WARN -- : TIME: 5.250779204 302 naming create user 50.45.202.103      https://mushroomobserver.org/naming/create/335734?approved_name=        Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
I, [2022-08-29T18:19:54.153476 #1418701]  INFO -- : Started GET "/335734" for 50.45.202.103 at 2022-08-29 18:19:54 +0000
I, [2022-08-29T18:19:54.155268 #1418701]  INFO -- :   Parameters: {"id"=>"335734"}
W, [2022-08-29T18:19:56.034572 #1418701]  WARN -- : TIME: 1.879114661 200 observations show user 50.45.202.103  https://mushroomobserver.org/335734     Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
```

Bug 2: Cannot modify a Proposed Name for certain Observations.
- Login to the website
- Switch to Admin Mode
- Switch Users to `heelsplitter`
- Goto https://mushroomobserver.org/303029
- Under the Proposed Name _Polyporaceae_, click Edit. 
(As of this writing, heelsplitter is the only user who has voted on the proposal.0
- Change something. E.g., change the Confidence Level to "Not Likely"
- Save Edits
Result: "The page you were looking for doesn't exist."
<img width="650" alt="Screen Shot 2022-08-29 at 1 20 30 PM" src="https://user-images.githubusercontent.com/45460/187291037-287780ef-7c56-4b4e-8d1a-556310d0fd22.png">

Production Log entry:
```ruby
I, [2022-08-29T20:46:25.039410 #1418701]  INFO -- : Started GET "/303029" for 50.45.202.103 at 2022-08-29 20:46:25 +0000
I, [2022-08-29T20:46:25.041248 #1418701]  INFO -- :   Parameters: {"id"=>"303029"}
W, [2022-08-29T20:46:26.899092 #1418701]  WARN -- : TIME: 1.857646812 200 observations show user 50.45.202.103	https://mushroomobserver.org/303029	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:103.0) Gecko/20100101 Firefox/103.0
```

**Comment by pellaea** [comment]
The button looks fine:

<input type="submit" name="commit" value="Create" class="btn center-block"
style="margin-top:2em" data-disable-with="Create" />

It must be related to javascript?

**Comment by JoeCohen** [comment]
The DELETE might be a red herring (or maybe a third issue).
The DELETE might be the result of Django independently trying to destroy the proposed naming. 
(I think 67.143.128.165 is Django. All the log entries I quoted were from 50.45.202.103, which is me.)

**Comment by pellaea** [comment]
No, that was from when I duplicated the bug.  I definitely didn't try to
delete anything.  I'm saying that the button shown here:

<input type="submit" name="commit" value="Create" class="btn center-block"
style="margin-top:2em" data-disable-with="Create" />

resulted in a DELETE request.  That is not in the page's initial HTML, so
therefore it must have been added later somehow.  Ergo, javascript must be
involved.  Or so goes my reasoning.

Maybe Nimmo knows something about it.  Remember we have some sort of gem or
what-not that simulates DELETE requests with javascripts.  This was a
necessary step toward getting the new-fangled fancy-shmancy CRUD routes to
work.  I would personally start there.

If I had time.  I was just hoping it would be something easy... :(

**Comment by JoeCohen** [comment]
Grasping at straws:
1. Changed cookie configuration. In July we changed the cookie figuration.
We thought it might cause some disruption, but things went smoothly.
Is it possible that it affected only Django?
https://github.com/MushroomObserver/mushroom-observer/pull/1073
https://github.com/MushroomObserver/mushroom-observer/issues/1071
2. Could it be something in his session? If so, is there a way to clear
that?

**Comment by pellaea** [comment]
In both cases, I would say "no", because we can reproduce it on other
browsers.  But we do have to be logged in as him, so maybe there's a
difference in his user preferences?  But I don't think it can have anything
to do with cookies or session (those are stored on his browser and wouldn't
be reproducible).

**Comment by pellaea** [comment]
More data to stir into the pot.  Hopefully it makes more sense to you!

ExplorerDJ is having the same problem.  She's trying to propose a name
(apparently any name will do) to observation 484606 with the same result.
In both cases (335734) I can propose the name just fine, either as an admin
or not (I temporarily removed my admin status).  I even set all my
preferences to be identical to Joana's (ExplorerDJ), no change.  Django is
allowed to propose names for Joana's observation and vice versa.  Although
note that "Django's" observation is actually Pulk, so ownership has nothing
to do with it.  In both cases the problem user already has a name proposal
for the observation.  What else is the same?

I think we're barking up the wrong tree by trying to find out what
conditions are triggering this obscure bug.  I think we need to be tracing
the actual execution -- i.e. in javascript! -- to find out why that button
is making a delete request sometimes.  We need to take advantage of this
rare opportunity of actually being able to reproduce this bug reliably.

I take it I'm the only one who remembers that we added JS to convert
buttons to send DELETE requests?  I'll see if I can track that code down
and insert some diagnostics...

**Comment by pellaea** [comment]
Aha!  I got it!  I know the condition at least that's causing this!  Notice
that whenever there is a "Destroy Sequence" button on the "Propose Name"
page, it will fail.  Django created the sequence on 335734, that's why he
cannot propose a name for that observation.  Joana created a sequence for
484606, that's why she cannot propose a name for that observation.  But
note that you can I can propose names for either, unless we are in admin
mode, then we, too, get the "Destroy Sequence" button on that page and can
no longer propose a name for either observation.

The "Destroy Sequence" button is dickering with the hidden _method field.
It creates a big old form with all sorts of hidden fields and stuff to make
that work:

<form class="button_to" method="post"
action="/sequences/5223?back=%2Fsequences"><input type="hidden"
name="_method" value="delete" autocomplete="off" /><input
class="text-danger" data-confirm="Are you sure?" type="submit"
value="Destroy Sequence" /><input type="hidden" name="authenticity_token"
value="IV5dYv2X/xRlDVlfwNbA1j5Ub5HW3fj/KqVKd7xcGdMlGs1kpNckWkLtheddUPluzkTnHFTpApb83zPB3rcTTQ=="
autocomplete="off" /></form>

Notice that this is completely enclosed (note the closing </form> tag), so
this *shouldn't* affect the other form.  But it is for some reason.
Somehow or other that's where the bug is happening.

**Comment by pellaea** [comment]
Note that the "Destroy Sequence" button-form is inside of the naming/create
form.  Here's one really quick thing to try -- move the show_observation
partial outside of the naming/create form.  Maybe that will be enough to
get it to start working?

**Comment by pellaea** [comment]
Oh, it may be even simpler than that.  There is an imbalance in <div>s in
that form.  I'm creating a PR for it right now...

**Comment by JoeCohen** [comment]
Wow!

**Comment by pellaea** [comment]
It wasn't.  But moving the partials outside of the form *did* work.

One down.  What was the other?...  Oh, the edit form is also broken.  Easy
enough...

**Comment by JoeCohen** [comment]
Fixed by @pellaea, PR #1136 #1137

**Comment by JoeCohen** [comment]
This is so weird.
A. If I login as me, go to Obs 335734, and propose a Naming it works just
fine -- it POSTs
B. But when simulating Django (in the same browser that I used for A) it
generates a DELETE.
How can that be?

**Comment by pellaea** [comment]
The log shows that for whatever reason it's posting a DELETE request:

Started DELETE "/naming/create/335734?approved_name=" for 67.143.128.165 at
2022-08-29 20:57:36 +0000

No such route exists, of course, thus the error message.
