### ISSUE TITLE
Edit Classification help_block renders incorrectly

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#1455]
The class renders as text instead of as a tag.
Ex: https://mushroomobserver.org/names/58195/classification/edit
>`< class="help-block">List the higher taxa containing this family, one name per rank. Do not include genus or lower ranks. ...`

I also wonder if this should be translated (i.e. called with `.t` rather than `.l`.)

**Comment by JoeCohen** [comment]
@nimmolo Although this is low priority, it looks funky.

**Comment by pellaea** [comment]
Yes, that should definitely be `.t` not `.l`.

**Comment by nimmolo** [comment]
Thanks all - case closed
