### ISSUE TITLE
Descriptions missing from Name page in Admin mode

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#1457]
Ex: For https://mushroomobserver.org/names/63714
Compare non-admin view
<img width="366" alt="Screenshot 2023-04-08 at 8 46 39 AM" src="https://user-images.githubusercontent.com/45460/230730449-938936bd-97eb-49b5-be04-9d717fc18de0.png">
with
Admin view:
<img width="315" alt="Screenshot 2023-04-08 at 8 48 05 AM" src="https://user-images.githubusercontent.com/45460/230730536-42b188bb-a81c-4f7b-a164-b6334c225843.png">

**Comment by JoeCohen** [comment]
Could this be related to the fact that the Descriptions shown in non-admin mode have no content?

**Comment by pellaea** [comment]
Bizarre!  Admin mode has fewer privileges!

**Comment by nimmolo** [comment]
Note: I've been slowly de-escalating privileges for admins, as I go through the code.

/jk

**Comment by nimmolo** [comment]
Ok. Here's a clue, maybe you guys can help.

The array of links is generated by this method. It seems `admin` may not qualify as a `reviewer?` - we need an alternative conditional `in_admin_mode?` here.

```ruby
# descriptions_helper.rb
  # Show list of name/location descriptions.
  def list_descriptions(object:, fake_default: false)
    user = User.current
    # Filter out empty descriptions (unless it's public or one you own).
    list = object.descriptions.includes(:user).select do |desc|
      desc.notes? || (desc.user == user) ||
        reviewer? || (desc.source_type == :public) # || in_admin_mode?
    end

    list = sort_description_list(object, list)

    make_list_links(list, fake_default)
  end
```

**Comment by pellaea** [comment]
Looks like someone explicitly excluded admins.  Weird.  Maybe it was a
testing thing and just never got reinstated?

**Comment by nimmolo** [comment]
@pellaea I just added that commented out `|| in_admin_mode?` to show where i'd put it

**Comment by pellaea** [comment]
Ha!  Got it.
