### ISSUE TITLE
Prefered Name is erroneously escaped in show_observation Title

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#1609]
@nimmolo: To replicate, view any Observation where the consensus ID is deprecated.
Example:
https://mushroomobserver.org/529367
The title displays as
<img width="925" alt="Screenshot 2023-09-12 at 5 09 25 PM" src="https://github.com/MushroomObserver/mushroom-observer/assets/45460/51fafab4-d584-4721-b812-8bfcc4b54e20">

**Comment by nimmolo** [comment]
Thanks, I believe this is a regression. I just tried to fix this yesterday.

**Comment by JoeCohen** [comment]
Perhaps it's correct in the main branch but the fix hasn't been deployed?

**Comment by nimmolo** [comment]
OH! of course. Thank you! Was about to get confused. I will deploy
