### ISSUE TITLE
Auto GPS + datetime extraction not working

### ISSUE THREAD

**Issue by Lodorenos** [MushroomObserver/mushroom-observer#1641]
Hi, when using the image uploader I see errors in the console.

![image](https://github.com/MushroomObserver/mushroom-observer/assets/2823835/2f33f712-05a1-4151-a230-50ceca48a53d)

![image](https://github.com/MushroomObserver/mushroom-observer/assets/2823835/91dcdff4-7c98-4b4c-b3e8-1ad060faecf6)

The variable is defined as a constant and assigned a new value afterwards. This fails, preventing the extraction of location and GPS data.

Link to code:
https://github.com/MushroomObserver/mushroom-observer/blob/main/app/assets/javascripts/mo_multi_image_uploader.js#L290

I can create a PR later today, unable to do so now.

**Comment by nimmolo** [comment]
Thanks Lodorenos! 

I got it, will handle now.

**Comment by nimmolo** [comment]
@Lodorenos If you get a chance can you please email me an example image of yours to test with? I think my test images don't have the necessary data. `andrnimm @ fastmail.fm`

**Comment by nimmolo** [comment]
fixed by #1643
