### ISSUE TITLE
Cannot edit Obs; "Save Edits" button inactive

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#1687]
I cannot edit any of my Observations because the "Save Edits" button is inactive/greyed.
<img width="768" alt="Screenshot 2023-11-10 at 9 17 44 AM" src="https://github.com/MushroomObserver/mushroom-observer/assets/45460/5bed9374-9347-4437-9e58-f4821635307a">

**Comment by nimmolo** [comment]
I tried to edit an observation just now, it took a long time for the button to un-grey, but it did, and I was able to “Save edits".

I dont’ find any JS errors in the console on the edit page, do you Joe? Not sure what’s up.

But I’m about to head out (to look for mushrooms!)

**Comment by mo-nathan** [comment]
I agree that the graying out of the Save Edits/Create buttons for various objects don't work quite correctly.  I have run into this problem several times while working on projects.  I generally get around it by toggling some checkbox or other widgets that re-enables it.  It needs to get fixed.  The worst specific case that I believe I have already reported is making changes to the location information using the Google Maps UI.

**Comment by nimmolo** [comment]
@mo-nathan I just fixed the submit grey-out yesterday on the obs form and I understand the issue better, but i believe you are talking about the locations on the project form, is that right?

I can take a look at it now if that's the case. I will probably not make the meeting today.

**Comment by nimmolo** [comment]
LOL that just shows how unfamiliar i am with projects. No map on the project form!
