### ISSUE TITLE
Location Merge requests not received by Webmaster

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#1701]
1. It appears that Location Merge requests stopped reaching the webmaster inbox shortly after Aug 15.
Details below.
2. I wonder if there's also a problem with other similar emails, e.g., requests to modify Names having dependents.

-----
Duplicate location merge requests
2 messages
Igor Safonov <igs109@yahoo.com>
To: "jdcohenesq@gmail.com" <jdcohenesq@gmail.com>
Hello, Joseph:-
Wed, Nov 29, 2023 at 5:42 PM
Please let me know whether the MO administration is still interested in removing duplicate geographic locations from the website. Since Jason is no longer active in dealing with this problem (at least for the time being), it appears that many of my merger requests filed since mid-August have not been acted on. Do you actually receive these requests anyway?
I hope all is well with you and Jason, and wishing you both a peaceful end of the year.
Very best, Igor

> Joseph Cohen <jdcohenesq@gmail.com>
To: Igor Safonov <igs109@yahoo.com>
Cc: MO Webmaster <webmaster@mushroomobserver.org>
Igor:
Thanks for your email.
Thu, Nov 30, 2023 at 1:20 PM
> 1. I am indeed still interested in removing duplicate geographic locations. While Jason has reduced his activities, he may also be interested.
>2. I automatically receive copies of these requests.
>3. It looks like the reason we didn't act on merger requests after August 10 is that none of those requests appear in the webmaster inbox!
I checked the spam folder and the filters, and there's nothing there. So there's some kind of bug. It will take me a while to investigate.
Joe

**Comment by JoeCohen** [comment]
This bug probably affects other automatically generated emails.
The most recent Request to Change Names Having Dependents in the webmaster inbox is Aug 16.

**Comment by JoeCohen** [comment]
PR Review Requests?

**Comment by nimmolo** [comment]
should be fixed by #1705

**Comment by JoeCohen** [comment]
Thanks for fixing this!
