### ISSUE TITLE
Autocomplete failing for "Sowerbyella"

### ISSUE THREAD

**Issue by mo-nathan** [MushroomObserver/mushroom-observer#1706]
When I try to create an observation the autocomplete functionality for names goes weird when I try to find the genus "Sowerbyella".  As I initially typed, the genus popped up briefly, but then was replaced a list of seemingly unrelated names that start with the letter "S" starting with "Scleroderma geaster var. socotranum" (see attached image).  This appears to be a JavaScript bug since I was able to reproduce it locally and the only rails activity is:

```
Started GET "/ajax/auto_complete/name/so" for ::1 at 2023-12-12 06:49:02 -0800
Processing by AjaxController#auto_complete as */*
  Parameters: {"type"=>"name", "id"=>"so"}
[globalite] HTTP header = "en-US,en;q=0.9"
[globalite] client accepted locales: en-US, en
[globalite] trying to match locale: en
[globalite] language match: en
[I18n] loading locale: en from request header
  Language Load (1.2ms)  SELECT `languages`.* FROM `languages` WHERE `languages`.`locale` = 'en' LIMIT 1
[I18n] Locale set to en
  User Load (0.6ms)  SELECT `users`.* FROM `users` WHERE `users`.`id` = 1 LIMIT 1
   (45.7ms)  SELECT DISTINCT `names`.`text_name` FROM `names` WHERE (`names`.`correct_spelling_id` IS NULL) AND (`names`.`text_name` LIKE 's%')
TIME: 0.075139 200 ajax auto_complete user ::1	http://localhost:3000/ajax/auto_complete/name/so	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Completed 200 OK in 75ms (Views: 0.3ms | ActiveRecord: 47.5ms | Allocations: 34421)


::1 - - [12/Dec/2023:06:49:02 PST] "GET /ajax/auto_complete/name/so HTTP/1.1" 304 0
http://localhost:3000/observations/new -> /ajax/auto_complete/name/so
```
<img width="313" alt="Screenshot 2023-12-12 at 6 42 23 AM" src="https://github.com/MushroomObserver/mushroom-observer/assets/3211730/75d2b2dc-0efd-4e69-8b42-791fcc2c5b0a">

**Comment by mo-nathan** [comment]
There's a comment in app/assets/javascripts/mo_autocompleter.js that says:
```
// MOAutocompleter makes a request at the very first letter, and our server                                                            
// returns *the first 1000 entries* corresponding to that letter.                                                                      
```
This could be part of the issue since there are 2604 names that start with "s".  However, I don't see where that limit is implemented.  Furthermore, the code in app/classes/auto_complete/for_name.rb claims:
```
    # (this sort puts genera and higher on top, everything else                                                                        
    # on bottom, and sorts alphabetically within each group)                                                                           
```
which implies to me that the "Sowerbyella" should be in the list of 1000 regardless.  I also note that "Sowerbyella rhenana" does appear in the list as soon as I've typed "Sowerbyella r", but no new database query is sent.

**Comment by nimmolo** [comment]
Thank you for the thorough documentation. 
#1708
