### ISSUE TITLE
N+1 queries in the Observation Namings/Votes table

### ISSUE THREAD

**Issue by nimmolo** [MushroomObserver/mushroom-observer#1722]
Just audited the effects of a single `change_vote` action on the Namings "table" in the show obs view, and realized that changing a vote (or proposing a naming) is slow because it currently initiates a cavalcade of N+1 queries. 

On an observation with 3 namings, changing the vote on a single naming resulted in 11 separate queries of the Votes table, plus plenty of other duplicate Naming, Observation and User queries. The `Votes` queries are the slowest, at about 350ms per query: 4s of extra delay to get the result of a single vote.

The situation seems to result from two inefficiencies in the code:
- There are many convenience methods of the Observation and Naming models that count naming votes, each of which initiate a separate query: `users_vote`, `owners_vote`, `user_voted?`, `owner_voted?`, `name_been_proposed?`, `owners_favorite?`, `users_favorite?`, `owner_votes`, `user_votes` etc.
- These methods are used repeatedly in both the controller and the helpers that render the Namings table. My recent refactors certainly didn't help.

#### PORO? ivar? ####
One thing that might help is to encapsulate an Observation's namings and the namings' votes into a single PORO whose data could be instantiated by a single query:
```ruby
@observation = Observation.includes(:user, :name, { namings: [:name, :user, { votes: :user }] }).find(:id)
poro = ObservationNamingVotesPORO.new(@observation)
```
Sort of a disposable snapshot of the Observation, a non-ActiveRecord model. Then we'd move all the convenience methods to the object itself, and they could only access that data (rather than accessing AR model methods that would be tempted to **look up** associations on the `Observation` or `Naming` record). 

That disposable snapshot could be passed around, and the data accessed in different ways, without incurring new lookups. But is that even a thing  — an object that temporarily caches a record and certain of its associations?

Does this [non-ActiveRecord Model](https://guides.rubyonrails.org/active_model_basics.html#model) seem like a good idea? Is the data in the object going to get stale during the time it's used?

Or am i overthinking it, and i can just cache all that stuff on the ivar `@observation` if i define it with all the includes?

Did i just "reinvent" the ivar? Lol. A quick trip to the console indicates that maybe i did.... but the trouble is that calling the methods like `user_voted?` on the ivar still incurs new `vote` lookups. Please help me figure this out.

#### `calc_consensus` ####
This expensive method reloads the Obs, uses a PORO to calculate and cache the consensus name on the Observation, and `announces_consensus_change` (queues emails). But the callers of this method usually want to use the reloaded observation itself, and they have to reload it themselves. The method could return the reloaded Observation, saving the caller a lookup.

#### `load_for_show_observation_or_goto_index` ####
This method attempts to load all the necessary associations to render an obs — particularly for naming forms. But it doesn't include all the Naming associations I just listed above, unscientific but certainly a minimum necessary. Maybe this is the place to start?

**Comment by JoeCohen** [comment]
Sorry, no clue.
