### ISSUE TITLE
Edit Location zaps existing geolocation

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#1727]
Clicking the Edit Location button automatically zaps existing lat/lon (and probably alt).
(This tends to be destructive. Although the old geoloc is technically preserved via versioning, 
we can't tell if a lat/lon change is deliberate or the result of the bug. It's a pain to restore the geoloc.)
Example:
1. goto https://mushroomobserver.org/locations/401
result: 
<img width="648" alt="Screenshot 2023-12-17 at 7 34 27 PM" src="https://github.com/MushroomObserver/mushroom-observer/assets/45460/918011ec-d42c-4291-83df-b30956ad66d5">
2. Click "Edit Location"
result: MO automagically destroys the existing geoloc
<img width="626" alt="Screenshot 2023-12-17 at 7 35 03 PM" src="https://github.com/MushroomObserver/mushroom-observer/assets/45460/aca4b818-009a-424d-b837-090d910b245c">

**Comment by nimmolo** [comment]
This should be a pretty easy fix, once i can focus on it. There's probably a line that replaces the nsew bounds with those loaded from Google on map open, that needs to be moved. On Dec 17, 2023, at 7:46 PM, Joseph D. Cohen ***@***.***> wrote:﻿
Clicking the Edit Location button automatically zaps existing lat/lon (and probably alt).
(This tends to be destructive. Although the old geoloc is technically preserved via versioning,
we can't tell if a lat/lon change is deliberate or the result of the bug. It's a pain to restore the geoloc.)
Example:

goto https://mushroomobserver.org/locations/401
result:

Screenshot.2023-12-17.at.7.34.27.PM.png (view on web)
2. Click "Edit Location"
result: MO automagically destroys the existing geoloc
Screenshot.2023-12-17.at.7.35.03.PM.png (view on web)

**Comment by nimmolo** [comment]
I believe this is fixed by #1729

**Comment by JoeCohen** [comment]
You're right. Thanks so much for doing this.
