### ISSUE TITLE
Failing system test assertion about ObservationForm year.

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#1764]
CI fails 100% because of the following.
The assertion at ObservationFormSystemTest line 17 fails 100% of the time in CI and locally, even though the app behaves correctly. (it fails regardless whether run individually or as part of a larger group of tests (e.g., `test:all, test:system`). )

### The assertion fails.
```ruby
% rails t test/system/observation_form_system_test.rb:17
Started with run options --seed 32457

[Screenshot Image]: /Users/joe/mushroom-observer/tmp/capybara/failures_test_create_minimal_observation.png-=---=---=---=---=---=---=---=---=---=---=---=---=---=---=--] 0% Time: 00:00:00,  ETA: ??:??:??
 FAIL ObservationFormSystemTest#test_create_minimal_observation (10.87s)
        expected to find visible field "observation_when_1i" that is not disabled with value "2024" within #<Capybara::Node::Element tag="form" path="//HTML[1]/BODY[1]/DIV[1]/DIV[2]/DIV[1]/MAIN[1]/FORM[1]"> but there were no matches. Also found "", which matched the selector but not all filters. Expected value to be "2024" but was "2023"
        test/system/observation_form_system_test.rb:17:in `block in test_create_minimal_observation'
        test/system/observation_form_system_test.rb:15:in `test_create_minimal_observation'
```
 
The relevant lines of the test are:
```ruby
    click_on("Create Observation")

    assert_selector("body.observations__new")
    within("#observation_form") do
      # MOAutocompleter replaces year select with text field
      assert_field("observation_when_1i", with: Time.zone.today.year.to_s)
```

It fails even if I `sleep(10)` just prior to the assertion. 

### The app behaves correctly.

If I run the app it behaves correctly:`2024` appears in the year field, and Observations are created with the correct year.
But the developer console is strange. In particular, a search for "2024" has no relevant hits.
<img width="744" alt="Screenshot 2024-01-01 at 4 41 41 PM" src="https://github.com/MushroomObserver/mushroom-observer/assets/45460/b75271f2-da19-49b9-b05c-9983c3baaf97">

**Comment by nimmolo** [comment]
That's weird alright. If I break in the test, I get:

```
(ruby) Time.zone.today.year.to_s
"2024"
(ruby) find("#observation_when_1i").value
"2023"
```

So the form is filling in the date with last year. `app/views/observations/form/_when.html.erb` calls `date_select_opts(@observation)`. If I break within that helper:

```
   443|   def date_select_opts(obj = nil)
=> 444|     debugger
   445|     start_year = 20.years.ago.year
   446|     init_value = obj.try(&:when).try(&:year)

obj.when
Sun, 19 Nov 2023
```
The issue is that the new observation is initialized with the old date from last year. Hmm.

**Comment by JoeCohen** [comment]
Yup. I couldn't figure out the source of "2023".

Could you get by with just a capybara integration test:
```ruby
  def test_new_observation_year
    user = users(:dick)
    login(user)

    visit(new_observation_path)
    assert_select("observation_when_1i", text: "2024")
  end
```

**Comment by nimmolo** [comment]
Ok. This is one of those interesting cases where the system test is showing up an issue in our code, not the other way around.

The obs date is getting set in `ObservationsController::NewAndCreate#defaults_from_last_observation_created`. For any new observation we are grabbing `when`, among other atts, from the last obs created. 

In the test suite, that date seems to be `19 Nov 2023`. 

```ruby
  def defaults_from_last_observation_created
    # Grab defaults for date and location from last observation the user
    # created if it was less than an hour ago
    # (i.e. if its creation time is larger than one hour ago)
    last_observation = Observation.where(user_id: @user.id).
                       order(:created_at).last
    return unless last_observation && last_observation.created_at > 1.hour.ago

    %w[when where location is_collection_location gps_hidden].each do |attr|
      @observation.send("#{attr}=", last_observation.send(attr))
    end
```

I'm not sure how to fix. I'm noticing we don't grab the last-used values `unless` the last obs was created more than an hour ago. I imagine that's to facilitate logging obs from awhile back. But maybe there should also be an upper limit, like "use today's date if the last obs was more than a week ago" or a month, or ...?

I'll leave this to you to fix, if you don't mind!

**Comment by JoeCohen** [comment]
Thanks for looking into this and figuring out the cause.
I expect the fix is easy:" pick a user with no Observations ("`zero`").
I'll give it a try.

**Comment by nimmolo** [comment]
Makes sense! And I wouldn't have thought of that so quickly.

By the way - the reason it's being tested by a system test is this:

The Rails "date picker" helper creates a "select" for the day, month and year, but like many other apps, MO prefers to have the year as a text field. Jason long ago wrote, and I recreated in Stimulus, a bit of JS replacing the year select with a text field. So that system test is making sure that replacement is happening.

**Comment by JoeCohen** [comment]
1. Thanks for the extended explanation.
2. The suggested fix works. (The right user is actually `zero_user`.). I'll get it merged.
