### ISSUE TITLE
Newly exposed lifeform issues

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#1787]
1. Cannot successfully edit lifeform. To replicate:
  - Show Name _Tremella mesenterica_. http://localhost:3000/names/40
  - Next to `Lifeform`, click the edit icon. 
    Result:  http://localhost:3000/names/40/lifeforms/edit
  - Check `Lichenicolous`
  - Click `Save`
  Result: Lifeform is unchanged.
2. Cannot successfully propagate lifeform. To replicate: 
  - Show Name _Peltigera_. http://localhost:3000/names/5077
  - Click `Propagate to Subtaxa` (goes to http://localhost:3000/names/5077/lifeforms/propagate/edit)
  - Check `Lichen`
  - Click `Apply`
Result: 
  >Routing Error
No route matches [POST] "/names/5077/lifeforms/propagate"

Issue "When it's a form_with(url:) we have to set the method: arg explicitly. For edit, that's put or patch. It defaults to post."
See https://github.com/MushroomObserver/mushroom-observer/pull/1783#issue-2071670503

**Comment by nimmolo** [comment]
@JoeCohen - I'll leave these two to you.
