### ISSUE TITLE
"Your Observations" is broken

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#1832]
Reported by users: When I click on "Your Observations" (ie. to see my observations) I get "no matching observations found." 
Some bug with "Your Lists"

**Comment by JoeCohen** [comment]
In app/views/controllers/application/_sidebar.html.erb the caches for these partials need to be customized for the user instance, rahter than the user status:
- application/sidebar/observations because it includes Your Observations 
-  application/sidebar/species_list because it includes Your Lists

**Comment by JoeCohen** [comment]
@nimmolo: The sidebar is partly broken. I thought I cold fix it, but I think I was wrong and have restored it to the partly broken state. 
Can you take a look?

**Comment by nimmolo** [comment]
Got it @JoeCohen, thanks. Will fix.

**Comment by nimmolo** [comment]
I think it's fixed. This unfortunately moves "News" below "Lists", but I hope it's worth it to minimize cache fragments.

**Comment by JoeCohen** [comment]
Thanks again.
