### ISSUE TITLE
Constraint Violations

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#1844]
A page, linked from the Project page, which
- Lists, in abbreviated form, the Observations which violate the Project's Constraints 
- For each violation, highlights the parameter(s) that caused the violation
- Allows removal via checkbox

Wire frame: (updated 2024-03-09) (needs submit button)
<img width="905" alt="Screenshot 2024-03-09 at 7 53 43 AM" src="https://github.com/MushroomObserver/mushroom-observer/assets/45460/2ad918cf-87cd-4072-8ebb-fb04708ec45f">

### Tasklist
- [x] Test and create link on Project page to violations page
- [x] Test violations index
- [x] Create violations page content
- [x] Fix Project page Observations button going to wrong place (goes to all Observations, rather than Observations for that project.)
- [x] Rearrange violations table (obs name, number, user, under "Constraints")
- [x] highlight individual parameter violations with css
- [x] Ensure lon styling proper if Proj.west > Proj.east
- [x] Highlighted Constraints button instead of flash warning for Show project page
- [x] Refactor Project#violates_date_range? using (start_date..end_date).cover?(observation.when)
- [x] Better top part of page? Title Constraint Violations., next line: Project: <project name>
- [x] Test that compliant Obs not listed in violations index
- [x] Hide lat/lon for unauthorized users
- [x] Add conditional checkboxes for Obss; condition: current user is project admin || created obs
- [x] #2022
- [x] Add `update` action
- [x] submit button(s)? Maybe "Remove checked Observations" conditioned on their being removable observations; Show Project; Maybe just "Submit"
- [x] Add instructions. (e.g., "Check Observations to be removed from Project."
- [x] Try moving app/helpers/table_helper.rb#violation_headers et seq. to a different helper
- [x] Font size same as Name, Observation stuff
- [x] If can't chack anything, hide help_text, change button
- [x] PR
- [x] ? Project vs Observation
- [x] ? Better name for "Violations"?
- [x] ? Better namespace for "Violations"?
- [x] ?`edit` vs `index`
- [x] ? how much code to include in form
- [x] ? font size same as left navbar
- [x] ? bg highlite: is there a style that works: with any User theme?  with screen width <= 766 px?
- [x] Change violations edit to index per https://github.com/MushroomObserver/mushroom-observer/pull/2021#discussion_r1519142331
analogous to 
```ruby
    observation_namings GET  /observations/:observation_id/namings(.:format)
edit_observation_naming GET  /observations/:observation_id/namings/:id/edit(.:format)                    observations/namings#edit
```
- [x] Do I need to specifiy the submission method in the form (app/views/controllers/projects/violations/index.html.erb)?
- [x] Try "Violations" button bordered, instead of changing bg.
- [x] check extent of form -- help text outside form.
- [ ] ? Reality check on obs.location within or == project.location. Note: Location of [Berry Field Access, Gifford Pinchot National Forest, Skamania Co., Washington, USA](https://mushroomobserver.org/locations/10210) is within [Oregon, USA](https://mushroomobserver.org/locations/1413?q=1pank)

**Comment by mo-nathan** [comment]
Ran into an interesting case today in the North Falmouth Fungi Project.  One of the observations (https://mushroomobserver.org/441113?q=1pZqa) is associated with the location [USA, Massachusetts, Falmouth, North Falmouth, Old Main Rd.](https://mushroomobserver.org/locations/23924) and the project is for the location [USA, Massachusetts, Falmouth, North Falmouth](https://mushroomobserver.org/locations/793).  The Old Main Rd. location had a slightly higher north lat which caused this observation to violate the project location constraint.  I'm not sure what the best way is to address this case, but it would have been helpful if I could have seen which observation was violating the constraint and what constraint it was violating.

**Comment by JoeCohen** [comment]
@nimmolo, @mo-nathan 
What should be the action names? Because there was a form involved I settled on edit/update. Alternatives include `index`, or something(s) unique.
