### ISSUE TITLE
Query getting lost on SpeciesListsController#show

### ISSUE THREAD

**Issue by nimmolo** [MushroomObserver/mushroom-observer#1849]
- Go to any Species List
- Click AddTo/RemoveFrom Another List
result: Flash Error
<img width="391" alt="Screenshot 2024-01-23 at 3 38 54 PM" src="https://github.com/MushroomObserver/mushroom-observer/assets/1948095/944c53ff-8909-438a-9dd6-268f24993a7c">

I think this is because the query param is not getting passed in, when the page is accessed (from where? -AN).

It could result from the species lists nav link in the sidebar being cached with a stale query. It's cached per user, but not the query record.

**Comment by nimmolo** [comment]
Should the sidebar link use the `query_from_session` or the `passed_query`?

**Comment by JoeCohen** [comment]
### JDC Tasks
- [ ] check coverage of SpeciesLists::Observations controller
- [ ] test to expose bug (probably a Capybara test)
- [ ] tidy?
- [ ] Fix bug
- [ ] Rubocop
