### ISSUE TITLE
Locations with hidden GPS

### ISSUE THREAD

**Issue by mo-nathan** [MushroomObserver/mushroom-observer#1945]
Use case: Foray on private land at a NAMA foray.

Locations get a new boolean value "hidden".
Only the owner (or an MO admin) can change the hidden boolean.  By default it is false.
When an observation is associated with a location, if the location is hidden, then the observation's GPS hidden boolean gets set to false.
Hidden bit cannot be changed if there are associated observations.
The coordinates of a hidden location are automatically rounded to the nearest 1/10 of a degree that makes the area larger.
Being the owner of a hidden location does not in and of itself grant the ability to see the GPS of associated observations.

**Comment by nimmolo** [comment]
This makes sense, i think.

**Comment by mo-nathan** [comment]
Yes.  I don't think it's worth maintaining enough state to do anything different than that.  I think it's a rare edge case with a reasonable way to address.

**Comment by mo-nathan** [comment]
I'm wondering if only MO admins should be able to set a location to hidden if there are already observations associated with it.  Unintentionally hiding a location with a lot of existing observations could make a big mess.
