### ISSUE TITLE
Confidence vote table is not updating on vote

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#1994]
user pinonbistro says:

> Confidence vote is not working.  See https://mushroomobserver.org/468517  where I said I'd call it Cortinarius trivialis group and the confidence is only 57%.  It change promising on Cortinarius sp. to 38%.

(I don't understand what the score should be.)

**Comment by nimmolo** [comment]
This sounds like it's working fine. There are three namings; they demoted their vote on one of them, and the percentage went down.

**Comment by JoeCohen** [comment]
@nimmolo. Something is broken. 
Example:
Locally, this is what http://localhost:3000/542837 initially looked like to me. (Oct snapshot,)
<img width="897" alt="54872 1" src="https://github.com/MushroomObserver/mushroom-observer/assets/45460/7446ff7e-e1fc-4693-9e55-942216d50014">

I then 
- Closed the Community Vote window/modal
- Added my own vote of Promising
- Reopened the Community Vote window//modal
The main window shows that there's one more vote, and that my vote is Promising. But nothing else has changed in either the main or modal.

**Comment by mo-nathan** [comment]
I haven't followed all of this conversation, but I know for myself, when I cast votes it often (usually? always?) doesn't update the consensus until I reload the page.

**Comment by nimmolo** [comment]
Checked into this a bit.  It's because we're using `modal_link_to`, which *re-opens* a modal *if it exists*. (Helpful in the case of a form in progress, but here it's preventing reload of the modal content)

We need to add something so that whenever the user casts a vote, we delete the `naming_votes_#{obs.id}` modal if it's in the DOM.
