### ISSUE TITLE
Coveralls node.js warning

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#2027]
We're geting this deprecation warning during CI 

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: coverallsapp/github-action@master. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by nimmolo** [comment]
Just checked our github settings in `ci_rails.yml` and I can't find where we have this configured.
Also poked around the GitHub repo for half an hour and I cannot find anything under Actions or Settings relating to this.

In "Settings", we seem to use "Webhooks" but not "Actions". (What is the difference? There's also "Runners".)
We also don't really execute any JS apps, just capybara. It is possible this will not affect our CI.

Joe - if you find where this "Coverallsapp" action lives, please let me know.

**Comment by JoeCohen** [comment]
I think there's nothing we can do about this (other than complaining to Coveralls and waiting for Coveralls to fix it.)
See https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/#for-actions-users
