### ISSUE TITLE
"Add" HR/CN buttons don't work after deleting previous record/number

### ISSUE THREAD

**Issue by nimmolo** [MushroomObserver/mushroom-observer#2039]
Workflow: 

- Show an observation (one of your own)
- Click the "+" to add a collection number or Fungarium record
- Delete it
- Click the "+" again to re-add one. 

You get a `500 server error`. I'm not sure why.

**Comment by mo-nathan** [comment]
Unable to reproduce.

**Comment by nimmolo** [comment]
Fixed. The issue was that after a turbo update of the "HR" section, the "+" buttons didn't get the observation ID to make a proper link to the `new` action.
