### ISSUE TITLE
refresh_all_user_stats Argument Error

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#2046]
Fix this error, which I seem to see daily
>Cron Daemon <root@mushroomobserver.org> Tue, Mar 19, 2024 at 10:14 PM
To: webmaster@mushroomobserver.org
`/var/web/mo/app/models/user_stats.rb:186`:in `refresh_all_user_stats`: wrong number of arguments (given 1, expected 0) (ArgumentError)
 from `script/refresh_caches:55`:in `progress`
 from `script/refresh_caches:78`:in `<main>`

**Comment by pellaea** [comment]
This is really easy.  Nimmo: I have structured all of the other nightly
refresh methods to accept a `dry_run` argument to allow easy testing from
the command line.  Just add that to your new method.
