### ISSUE TITLE
auto-checked Projects

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#2106]
The Field Slip α-Test  Porject is always selected when I create a new Obs.
I don't notice that because it's too far down on the form; I'd have to scroll down to notice it.
See screen shot below.
The result is that my new Observations unexpectedly are added to that Project (unless I remember to deselect it).
Is my expectation is wrong?
I expect no Project (or Species List) to be selected (unless I selected it in the last 60 minutes).
<img width="608" alt="Screenshot 2024-04-19 at 2 22 25 PM" src="https://github.com/MushroomObserver/mushroom-observer/assets/45460/e34e97d4-fffa-4d5f-86f7-947f7a04fa61">

**Comment by JoeCohen** [comment]
It's auto-checking every current, open Project of which I'm a member).
@mo-nathan: Maybe this should be user option?

In Observations#create
```ruby
  def init_project_vars
    @projects = User.current.projects_member(order: :title,
                                             include: :user_group)
    @project_checks = {}
  end

  def init_project_vars_for_create
    init_project_vars
    @projects.each do |proj|
      @project_checks[proj.id] = (proj.open_membership &&
                                  proj.current?)
    end
  end
```
In the form
```ruby
      <% @projects.each do |project| %>
        <%= check_box_with_label(form: f_p, field: :"id_#{project.id}",
                                 checked: @project_checks[project.id],
                                 disabled: !project.user_can_add_observation?(@observation, @user),
                                 label: project.title) %>
```

**Comment by mo-nathan** [comment]
Interesting question.  It is working as I intended it, but I can see some reason to debate it.  My thinking was for most users they will only be a member of small number of projects and it's reasonable to assume that if the project fits, the observation should get added.  For example, I would like to have "North Falmouth Fungi" to be selected any time I create an observation that is in North Falmouth.  Similarly, if I'm at the NAMA foray, I want all observations I make while I'm there to be automatically included in the NAMA foray project.  I'm pretty sure iNat does that during an event.  I guess the question comes down to what do we expect most users using the system to expect.

**Comment by JoeCohen** [comment]
Thanks. That rings a bell; you probably mentioned this earlier.
I will:
- solve my personal problem by removing myself from the alpha Field Test
Project
- close this issue.
