### ISSUE TITLE
"Report a Bug" broken

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#2115]
A user reports:

> 4. The link to Report a Bug is dead - page not found. [Samsung/Chrome]
[Mushroomobserver.org Mail - [MO] Question From jim.clack@gmail.com.pdf](https://github.com/MushroomObserver/mushroom-observer/files/15052637/Mushroomobserver.org.Mail.-.MO.Question.From.jim.clack%40gmail.com.pdf)

I cannot replicate this on my desktop or iPhone. I've asked the user to retry it.

**Comment by JoeCohen** [comment]
Jim Clark adds:
>Thanks for the quick reply. 
Samsung Galaxy 23fe
Attached: 
>1. The "report a bug" link as displayed in my phone.
>2. The page that comes up when I click it, whether I am logged in or not.

![Screenshot_20240421_131854_Chrome](https://github.com/MushroomObserver/mushroom-observer/assets/45460/ee45ff95-c7ae-4592-8d5a-ff68298f8998)
![Screenshot_20240421_131901_Chrome](https://github.com/MushroomObserver/mushroom-observer/assets/45460/f8a544ff-4f62-4e49-818e-0d4f0cd79e80)

**Comment by nimmolo** [comment]
I can't reproduce either. 
My suspicion is that it's the Chrome browser's overzealous caching. 

They can test by trying the link from an incognito window.
