### ISSUE TITLE
Add LicensesController

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#2151]
- Update MO's Creative Common licenses to v.4
- Add new licenses if appropriate

### License Controller TODO
- [x] Index
  - [x] Links
- [x] Show License
  - [x] Admin Only
  - [x] Links to: Add, Edit, Destroy if unused
- [x] New
  - [x] `Deprecated?` checkbox
  - [x] Links
- [x] Create
  - [x] Validate
- [x] Edit
  - [x] Links
- [x] Update
- [x] Destroy
- [x] Link in Admin Menu (lh navbar) to Index
- [x] Rubocop
- [x] Update documentation
  - [x] Translations
  - [x] Readmes
- [x] Update badges https://creativecommons.org/mission/downloads/
  - [x] Fix badges for existing licenses. They're not broken. It's a problem with my local settings. 
  - [x] Add badges and forms for new licenses. Ex: app/views/controllers/shared/_form_ccbyncsa25.erb
- [x] Consider new unicode symbols? https://creativecommons.org/2020/03/18/the-unicode-standard-now-includes-cc-license-symbols/ **Won't do**
- [x] Validate uniqueness of display_name, url
- [x] Flash validation errors.
- [x] params.deprecated: `true`/`false` or `1`/`0`
- [x] QUESTIONS
  - [x] no `created_at`, many lack `updated_at`
- [x] Add `created_at`
- [x] single, parametized, license badge partial to replace app/views/controllers/shared/_form_ccbyncsa25.erb, et al. See https://licensebuttons.net/
- [x] Revise index display. See https://github.com/MushroomObserver/mushroom-observer/pull/2154#discussion_r1623392075; also include "Default" if default license
- [x] Revise show display. https://github.com/MushroomObserver/mushroom-observer/pull/2154#issuecomment-2143816910; also include "Default" if default license
- [x] Revise form, showing Default if default license
- [x] Coverage of License model and Licenses controller
- [x] Rubocop
- [ ] Merge & Deploy
- [ ] Follow up with #2151

**Comment by mo-nathan** [comment]
Thanks for noticing this and adding the issue.

**Comment by JoeCohen** [comment]
iNat's explanation of its available licenses:

Edit License
Licensing your content gives anyone the legal right to use it without asking your permission if they abide by the terms of the license. In addition, iNaturalist includes your Creative Commons-licensed content in regularly-updated archives produced for select partner organizations interested in our data. For example, we include No Copyright (CC0), Attribution (CC BY), and Attribution-NonCommercial (CC BY-NC) records in the archive we generate for the [Global Biodiversity Information Facility](http://www.gbif.org/) (GBIF), an international, inter-governmental organization that compiles and distributes biodiversity information from around the world.

### Cc0No Copyright (CC0)
Good choice for sharing with scientists
This license releases your work into the public domain, so others can copy, modify, distribute and perform your work, even for commercial purposes, all without asking permission or giving you credit. This is the most accommodating of licenses offered. Recommended for maximum dissemination and use of licensed materials. [View License](http://creativecommons.org/publicdomain/zero/1.0/)

### Cc byAttribution
Good choice for sharing with scientists
This license lets others distribute, remix, tweak, and build upon your work, even commercially, as long as they credit you for the original creation. [View License](http://creativecommons.org/licenses/by/4.0/)
### Cc by ncAttribution-NonCommercial(your default)
Good choice for sharing with scientists
This license lets others remix, tweak, and build upon your work non-commercially, and although their new works must also acknowledge you and be non-commercial, they don't have to license their derivative works on the same terms. [View License](http://creativecommons.org/licenses/by-nc/4.0/)
### Cc by saAttribution-ShareAlike
This license lets others remix, tweak, and build upon your work even for commercial purposes, as long as they credit you and license their new creations under the identical terms. All new works based on yours will carry the same license, so any derivatives will also allow commercial use. [View License](http://creativecommons.org/licenses/by-sa/4.0/)
### Cc by ndAttribution-NoDerivs
This license allows for redistribution, commercial and non-commercial, as long as it is passed along unchanged and in whole, with credit to you. [View License](http://creativecommons.org/licenses/by-nd/4.0/)
### Cc by nc saAttribution-NonCommercial-ShareAlike
This license lets others remix, tweak, and build upon your work non-commercially, as long as they credit you and license their new creations under the identical terms. [View License](http://creativecommons.org/licenses/by-nc-sa/4.0/)
### Cc by nc ndAttribution-NonCommercial-NoDerivs
This license is the most restrictive of the six main licenses, only allowing others to download your works and share them with others as long as they credit you, but they can't change them in any way or use them commercially. [View License](http://creativecommons.org/licenses/by-nc-nd/4.0/)
### No license (all rights reserved)
You retain full copyright over your content aside from those rights granted to iNaturalist in our Terms of Use.
<img width="924" alt="Screenshot 2024-05-21 at 8 08 47 PM" src="https://github.com/MushroomObserver/mushroom-observer/assets/45460/bda0a7d1-32a3-422c-984c-26f8cf769c59">

**Comment by JoeCohen** [comment]
@mo-nathan, @pellaea, @nimmolo 
Should we make all of the above licenses (except No License) available on MO?

**Comment by JoeCohen** [comment]
@mo-nathan, @pellaea, @nimmolo
### What is the best practice for updating MO licenses?
Our licenses are in the db, not in the code. We have a License model, but no Licenses controller.

**Comment by JoeCohen** [comment]
@mo-nathan, @pellaea, @nimmolo

### Should we stop versioning licenses, instead alsway using Creative Commons' most recent version of a license?

I note that iNat does not version licenses.

**Comment by mo-nathan** [comment]
I'm fine with supporting all of these licenses (except No License).  The big questions are what do we do for the default license for new users and what do we do for existing users.  I think the best thing to do is switch the default license to the most current equivalent license and to update all users to use the most recent version of what is essentially the same license.  We should also not provide the option of selecting older versions of equivalent licenses.  Ideally we would also provide a way for users to bring all their existing licenses up to date, but I think that should require an explicit user action.  For users with a lot of images it may take a while so it's probably something that really should get done as a background operation.

**Comment by mo-nathan** [comment]
I'm ok with moving to the "most recent version of a license" if we let users know that's what we're doing.  It would be worth reading over the older versions of the licenses to see if they say anything about updates to the license.  If that's already a provision of the license, then we should be fine.  Otherwise, I think technically we have to let users opt-in to the upgrade, but we could potentially give them the option to have our system automatically update the license for folks who don't care (which I expect is most users).

**Comment by mo-nathan** [comment]
I don't see any obvious provision in the 3.0 by-sa license about updating the license.  I think this is common in click-through licenses where it says the license may be updated from time to time.  I think we need to make this an opt-in thing which we advertise through the banner or some such.

**Comment by JoeCohen** [comment]
Thanks for the feedback.
I want to add the "missing" licenses now in order to make it easier to
import iNat Observations.
My general plan.

   - PR to add admin-only controller & views. (I don't see any UI to add
   licenses, and I don't see any other easy way to update them.
   - Add new versions of existing licenses, deprecating older versions.
   - Add missing CC licenses.
   - Leave updating User preferences and current Image licenses for the
   future.

**Comment by mo-nathan** [comment]
A controller would be nice, but I'd probably just do it with a quick script that just creates the needed objects.  I note that the current DB only has 4 licenses.  Maybe we don't need to add all the ones that iNat has.  Don't have a strong opinion.

**Comment by JoeCohen** [comment]
I want to add the "missing" licenses, else importing iNat observations gets
unnecessarily complicated:
If we don't have the exact iNat license, then we need to map iNat Licenses
to a different MO equivalent, and also get the user's permission to use a
different license in MO.

**Comment by mo-nathan** [comment]
Good point.  That's fine.
