### ISSUE TITLE
Edit Proposed Name Confidence

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#2181]
Edit Proposed Name modal is initialized with Confidence == `I'd Call It That` if the Confidence Level had been `No Opinion`
To replicate:
- Propose a Name, leaving the Confidence Level blank
- Click the edit Proposed Name icon
Result: The Edit Proposed Name modal initializes with Confidence Level set to `I'd Call It That`. IMO it should be `No Opinion` or blank
<img width="674" alt="Screenshot 2024-06-16 at 6 24 59 AM" src="https://github.com/MushroomObserver/mushroom-observer/assets/45460/1cf7185f-41f6-4c0c-81bb-0c3ef8e132af">

(Requested by long-time power user Dave W.)
<img width="624" alt="Screenshot 2024-06-16 at 6 36 13 AM" src="https://github.com/MushroomObserver/mushroom-observer/assets/45460/591ba173-889c-4270-bbce-86189eb8c1dc">

**Comment by JoeCohen** [comment]
This is not a modal issue. The same thing happens regardless whether you use a modal.

**Comment by mo-nathan** [comment]
Seems reasonable to me.

**Comment by JoeCohen** [comment]
@mo-nathan Can you clarify?
Do you mean that the default (if confidence was No Opinion) should be:
- No Opinion
- I'd Call it That.

**Comment by mo-nathan** [comment]
In my view the current behavior is wrong. The value should default to the current value, not change when you go to edit.

**Comment by nimmolo** [comment]
Fix deployed
