### ISSUE TITLE
observations/map broken

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#2261]
Ex: (webserver, as of [757fb12](https://github.com/MushroomObserver/mushroom-observer/commit/757fb129278ec7c11466c7764412852f831021e1))
- Observation Pattern Search for `region:"Mendocino Co.\, California\, USA"` (Observations in Mendocino County).
Result: 40 pages of Observations
- Click `Show Map`
Result: 
<img width="355" alt="Screenshot 2024-07-27 at 7 36 43 AM" src="https://github.com/user-attachments/assets/f295ac62-04a9-418a-aa02-8170fb14e52a">

- Go back in browser.
Result: 40 pages of Obss, but with the loading icon: <img width="38" alt="Screenshot 2024-07-27 at 7 42 42 AM" src="https://github.com/user-attachments/assets/38c378e6-44ab-413a-9d15-513e64b46ea4">

Perhaps due to the large # of obss returned? It works fine for finer searches, e.g., this pattern search
`region:"Point Arena\, Mendocino Co.\, California\, USA"`

**Comment by JoeCohen** [comment]
Igor Safonov reports it's broken for Observations of _Amoenoboletus+weberi_, which has only 14 Observations.
https://mushroomobserver.org/observations?pattern=Amoenoboletus+weberi
We've also had a report about map issues from Crystal.

**Comment by JoeCohen** [comment]
@nimmolo, @mo-nathan:
Maps for Locations are completely broken on the webserver. There are no maps on either show Location or edit Location.
However maps do appear for Locations when I run locally.

**Comment by nimmolo** [comment]
The issue is that none of the JS is loading, currently. 

It may have something to do with a tiny bug in my new stimulus class inheritance - the way the file is loaded, specifically. Researching.

**Comment by JoeCohen** [comment]
Fixed. See https://mushroomobserver.slack.com/archives/C040TH9FV/p1722310511651789
