### ISSUE TITLE
Understand how Mirror authenticates iNat API requests

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#2295]
Maybe this will help me figure out how to authenticate iNat API requests for iNat imports.

-----
>Jacob K
>Thu, Aug 1, 1:52 PM (7 days ago)
>to me, MO
>
>Hi Joe,
>
> Oh boy, I remember a lot of frustration figuring out how it works in the first place, and in the 2 years(?!) since then I barely remember it.
>
>However, the code for my program is available on GitHub, it works and I'm hoping it might not be too hard for you to reconstruct it from that. Quick summary looking back at it:
>
> - Final request is made by the careful_request function in both_api.py
> - This is called by, say, the update_obs function in inat_api.py
> - For authentication the crucial part here is the JWT (a string that has to have been passed to the update_obs function)
> - Obtaining the JWT is a multi-step process that is fully completed by the get_JWT_PKCE function in inat_api.py
> 
> I would like to think the code in that function is clear enough - let me know how it goes!

>> On Thu, Aug 1, 2024 at 12:41 PM Joseph Cohen <jdcohenesq@gmail.com> wrote:
>> Dear Jacob:
>> 
>> Could you get some advice to help with a Mushroom Observer project I'm working on. It complements your MO to iNat Mirror; it will import iNat observations to MO.
>> 
>> I'm having trouble understanding/using the iNat documentation on authenticated iNat API requests. 
>> 
>> Would you mind sharing with me a complete (except for secrets, etc.) authenticated iNat API request, for instance
a request which writes "Originally posted to Mushroom Observer on xxx." in the Inat Notes field, or
a request which creates and fills the iNat "Mushroom Observer URL" observation field.
>> Best regards,
Joe Cohen
>> 
>> (I'm able to read and import all non-confidential iNat data. But I'm getting stuck on making an authenticated request to view all the data. 
I can obtain a code when the iNat user authorizes MO to access the user confidential iNat data.
I think I can trade the code for a token. (I may not be doing this properly.)
I try to use the token in an authenticated request to the iNat API (https://a pi.inaturalist.org/v1/).
I've tried using the older iNatAPI (https://www.inaturalist.org ) for the authenticated request, but that isn't working for me.)

**Comment by JoeCohen** [comment]
Mirror does this
```py
def careful_request(request_type, url, data = None, files = None, headers = None, demand_json = True):

    if url.startswith("https://api.inaturalist.org"):
        platform = "iNat"
    elif url.startswith("https://mushroomobserver.org"):
        platform = "MO"
    else:
        platform = None

    attempt = 0
    while attempt < MAX_ATTEMPTS:

        request_pause(platform, attempt)
        attempt += 1

        try:

            if request_type == "GET":
                response = sess.get(url, data = data, files = files, headers = headers)
            elif request_type == "POST":
                response = sess.post(url, data = data, files = files, headers = headers)
            elif request_type == "PUT":
                response = sess.put(url, data = data, files = files, headers = headers)
            elif request_type == "PATCH":
                response = sess.patch(url, data = data, files = files, headers = headers)
            elif request_type == "DELETE":
                response = sess.delete(url, data = data, files = files, headers = headers)
...
```

**Comment by nimmolo** [comment]
Joe - this really seems like it should also be possible, and maybe simpler, with their [old api](https://www.inaturalist.org/pages/api+reference#auth) written with oauth2 in Ruby. I'm surprised it's not working for you. Where does it stop working?

I imagine you're able to get the app token... then what happens?

**Comment by JoeCohen** [comment]
1. I've played around with the old API, but couldn't get the response I expected.
2. I'd like to keep trying the new API for now because it's better documented. There's also some guidance in the Mirror program.
3. I am able to exchange the a code for an token. When I make a request using the token either:
  The response does not include confidential data, e.g., lat/lng with private accuracy. (I get everything else). or
  I get an error. 
4. I may be missing a step. Pulk's Mirror script exchanges the token for a JWT, something I'm not doing because it doesn't seem to be part of the iNat documentation for the authentication protocol I'm using. But maybe I'm misreading things. And the Mirror script uses a different protocol.  I'll probably next try getting a JWT, then making the APi request.

**Comment by nimmolo** [comment]
Yeah, the JWT is what i was trying to help you avoid dealing with. It's a whole other level of complexity.

Does nobody on iNat respond when they get an email? They clearly state that you should be able to get confidential data with the old API, and I would think someone there should at least be able to tell you if that's not the case. (They also state that the old API can do more!)

**Comment by nimmolo** [comment]
I assume you've tried using the token with (i forgot the name of the online app that lets you test APIs) rather than sending via the code on your branch?

**Comment by JoeCohen** [comment]
The old API is plan B.

**Comment by JoeCohen** [comment]
Postman.
I've tried it via Postman.
But more often via my branch, or sometimes via the console (e.g., insert a
breakpoint in the code, then try things via the console.).

**Comment by nimmolo** [comment]
How long does a token last, by the way? I'd like to try it on Postman myself.

**Comment by JoeCohen** [comment]
24 hours.
