### ISSUE TITLE
Fix deprecated arel_extensions

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#2371]
arel_extensions: `==` is now deprecated and will be removed soon. Use `.eq` instead.  
arel_extensions: `!=` is now deprecated and will be removed soon. Use `.not_eq` instead.

**Comment by mo-nathan** [comment]
I dug into one of these and found that it happens on line 532 of UserStats.count_versions.  I think it might be a bug in the arel warning since that method already uses `.eq` rather than `==`.

**Comment by JoeCohen** [comment]
We do use at least `==` in a few places. I'll take a pass at this.
Example (app/controllers/names/eol_data/preview_controller.rb, line 52.
```ruby
                   where(Image[:ok_for_export] == true).
```

**Comment by mo-nathan** [comment]
I'd verify that running any test for this code triggers the warning.

**Comment by JoeCohen** [comment]
Sure. But we might as well fix the ones that actually are deprecated.

**Comment by JoeCohen** [comment]
The warning is not triggered by running `test/controllers` or `test/integration` on their own.
It is triggered by running `test\models`, and therefore is triggered by running the test suite.

**Comment by JoeCohen** [comment]
As of 2024-09-06, the chron jobs also are complaining:
>Cron Daemon <root@mushroomobserver.org>  Fri, Sep 6, 10:15 PM (2 days ago)
to me
arel_extensions: `!=` is now deprecated and will be removed soon. Use `.not_eq` instead.
Observation 558985, Fungi, needs a name.
Deleted 108 unverified user(s).
UserStats updated for 90097 users.
