### ISSUE TITLE
iNat votes without observation_view

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#2479]
Investigate the `User 55281 has reviewed observation nnnnnn` entries in this email. 
The Observations are all recent iNat imports. User 55281 is webmaster.
Probably failing to add/set something during import.

> Cron Daemon <root@mushroomobserver.org>
> Oct 8, 2024, 10:15 PM (8 hours ago)
> to webmaster
> 
> Observation 561902, Fungi, needs a name.
> Observation 561917, Fungi, needs a name.
> Observation 561920, Fungi, needs a name.
> User 55281 has reviewed observation 561908 (insert).
> User 55281 has reviewed observation 561908 (insert).
> User 55281 has reviewed observation 561908 (insert).
> User 55281 has reviewed observation 561909 (insert).
> User 55281 has reviewed observation 561909 (insert).
> User 55281 has reviewed observation 561932 (insert).
> User 55281 has reviewed observation 561936 (insert).
> User 55281 has reviewed observation 561938 (insert).
> User 55281 has reviewed observation 561938 (insert).
> User 55281 has reviewed observation 561939 (insert).
> User 55281 has reviewed observation 561939 (insert).
> Deleted 13 unverified user(s).
> UserStats updated for 91590 users.

**Comment by JoeCohen** [comment]
@nimmolo: Any ideas about an easy way to create an `observation_view` entry when a job creates a Naming and Vote?

When importing an iNat observation, `InatImportJob` creates MO Namings and Votes corresponding to iNat identifications.
```ruby
  def add_naming_with_vote(name:, user: inat_manager, value: Vote::MAXIMUM_VOTE)
    naming = Naming.create(observation: @observation,
                           user: user, name: name)

    Vote.create(naming: naming, observation: @observation,
                user: user, value: value)
  end
```
The Naming.user and Vote.user are generally (always?) `webmaster` rather than the MO user who imported the Observation. 
Result: The Votes do not correspond to an entry in `observation_views`. This needs later correction by `script/refresh_caches`. See [issue description above](https://github.com/MushroomObserver/mushroom-observer/issues/2479#issue-2576061864).

It would be nice to avoid that correction by have by creating `observation_views` entries when `InatImportJob` creates the Namings and Votes.

**Comment by nimmolo** [comment]
Use a model callback `before_save` on the vote or naming?

**Comment by JoeCohen** [comment]
Thanks for thinking about this and for the suggestion. 
It looks right on.
