### ISSUE TITLE
Add ability to filter project observations by location

### ISSUE THREAD

**Issue by mo-nathan** [MushroomObserver/mushroom-observer#2513]
As a user viewing a project, I should be able to filter the names based on relevant locations so I can share such lists with land owners/managers.

**Comment by JoeCohen** [comment]
How about this:
- Project has_many Locations (and probably vice versa) - easy
- Fix `Show Names` link on Observations index pages - probably hard

Use PatternSearch, **IF** a Project had many Locations. We could use the earliest-created Location as the Project's overall Location.
The UI could be something like:
- The Project page has a `Locations` button, similar to other buttons
- The button goes to a projects location page, which: lists Locations (each linked to the Location); has an Observations button per Location which button incudes an Observation count;
- That Observation button does a Pattern Search
- Click `Show Names` link (currently broken -- it shows all Names in the db) on the resulting `Matching Observations` page
![Image](https://github.com/user-attachments/assets/db7b65d7-5dab-42ef-9533-8b257cbb11b1)

**Comment by mo-nathan** [comment]
Fixed in #2591.
