### ISSUE TITLE
Fix Download Observations

### ISSUE THREAD

**Issue by JoeCohen** [MushroomObserver/mushroom-observer#2553]
To replicate:
- Observation pattern search for a reasonable number of Obss. Ex: https://mushroomobserver.org/observations?pattern=user%3A4468+date%3A2024-10 (@JoeCohen's Obss for 2024-10)
- Click `Download Observations`
Expected result: "Downloads" displayed Obss
Actual result: Flashes "You are trying to download too many Observations. Please see [CSV Files](https://github.com/MushroomObserver/mushroom-observer/blob/main/README_API.md#csv-files) for an alternative." because it's trying to download all Obss, rather than just the displayed Obss.

**Comment by JoeCohen** [comment]
PS: I found this bug after:
- noticing a post by Alan in the NAMA email group about a program (on the MO image server) which prints labels for iNat observations.
- wondering why MO doesn't have something like that for MO Observations (without having to create a Species List).

**Comment by JoeCohen** [comment]
The problem is that `too_many_observations?` is simply wrong:
```ruby
    def too_many_results?
      @query.flavor == :all
    end
```
The `:all` flavor does _not_ mean -- as I wrongly thought -- that the user is trying to download every Observation in the database. It's more like `all` Observations which meet the other search criteria, or something. 

###NOTE

- This means Download Observations has been broken for about 5 months (since #2214).
- Nobody has complained to me or webmaster about it.
- Ergo, nobody is using Download.

I do, however, want to fix it for possible use with MyCoPortal and GBIF.

**Comment by pellaea** [comment]
I'm curious why you are not doing something like this:

```
def too_many_results?
  @query.num_results > xxx
end
```

**Comment by JoeCohen** [comment]
Because I didn't know what I was doing.
I wrongly assumed that flavor :all meant that the user was trying to
download all the Obss in the db.
I'm now working on a fix: which will be
!inadmin_mode? && @query.num_results > xxx

What do you think is a good number?

**Comment by pellaea** [comment]
Haha, good reason!  No idea what a good number is.  Maybe start with 1000?

**Comment by JoeCohen** [comment]
Is there a way to test the fix without xxx new Observations? (seems like an
expensive test)

**Comment by pellaea** [comment]
How about make the limit a configuration which you can stub:

MO.max_download_observations
MO.stub(:max_download_observations, 5)

**Comment by JoeCohen** [comment]
Wait. I think I can just create nnn Obss without saving them, which makes
it not expensive.
Is that right?

**Comment by pellaea** [comment]
I don't think that's going to work.  Query needs to be able to find nnn
observations in the database, so they'll need to be saved.

**Comment by JoeCohen** [comment]
Interesting.
But the tests are passing if I use
(DownloadsController::MAX_DOWNLOADS - Observation.count + 1).times do
Observation.create(user: rolf)
end

I guess that does save to the db? The tests seem to be quick, and I don't
have to get involved with ugly stubs.

>

**Comment by pellaea** [comment]
Yes, create saves them.  Maybe it is somehow doing them in bulk.  Whatever
works.

**Comment by nimmolo** [comment]
@JoeCohen re `flavor: :all`
Note for the future that the goal we are halfway towards is for `flavor: :all` not to mean anything anymore. The flavor will be in the params.

`:Article, flavor: :by_rss_log, rss_log: xyz` is now `:Article, flavor: :all, rss_log: xyz`, and 
a query like `:Observations, flavor: :for_project, project: xyz` will soon be `:Observations, flavor: :all, project: xyz`

When they're all converted to params, then we'll get rid of `flavor` entirely.

**Comment by JoeCohen** [comment]
Maybe it's fast because I set nnn low. (120).
