### ISSUE TITLE
Fix Broken URLS in Returned in API2 XML Response

### ISSUE THREAD

**Issue by joshuamcginnis** [MushroomObserver/mushroom-observer#815]
Observation urls returned in the api2 xml high-detail response are broken (missing a `/`). An easy way to confirm this would be to construct a GET response with a test user:
https://mushroomobserver.org/api2/observations.xml?user=123&detail=high&page=1&api_key=api_key

The observation result nodes look like so:
```xml
<result id="421653" url="http://mushroomobserver.orgobserver/show_observation/421653" type="observation">
```

Note how there is a missing trailing slash after the domain. Config currently sets `http_domain` without a trailing slash so perhaps the easiest fix would be to add the trailing slash in the `show_url` method:

https://github.com/MushroomObserver/mushroom-observer/blob/7aa068418b9707b747b0d16b278d90377a0b33b6/app/models/abstract_model.rb#L439-L445

This bug is potentially impacting certain emails that may be referencing observation emails as well. 

As a [workaround](https://github.com/inaturalist/inaturalist/commit/3b6f9d36db2ac5884ece4bb0c7439c5f194dd62e), iNaturalist adds an individual call to each observation url and reconstructs it in it's MO import tool. Fixing this should allow iNat to trust the urls again, eliminating the costly calls to each url and greatly speeding up the imports.

**Comment by pellaea** [comment]
Thank you, Josh.  This should be trivial to fix.  I'm just struggling to
understand why it works for some objects but not others, considering it's
all using the same method!

**Comment by JoeCohen** [comment]
This may be a bug that was introduced when I refactored the herbaria
controller.
I think I had to somewhere add or remove a slash in order to get namespaced
controllers to work properly.

**Comment by joshuamcginnis** [comment]
It looks like the slashes were removed in https://github.com/MushroomObserver/mushroom-observer/commit/a452c3c3b505c6445a03fcf11bcf4f038bf238e4 for #740 as @JoeCohen suspected.

**Comment by joshuamcginnis** [comment]
I'm wondering if while this is being fixed, could we also go ahead and add image_url to the api response xml? This would save clients like iNat from even having to worry about when the url changes (such as the recent one which is contributing to the iNat MO import tool breaking). Happy to open a separate issue for this if needed.

**Comment by pellaea** [comment]
Actually, the bug, as it turns out, goes back to when we switched versions
of rails and had to anchor controllers with a leading slash.  Whatever,
it's not important, I've fixed it.

I'd be happy to add the image url.  Which end point and detail level are
you talking about?  I should probably know the answer to this, but I'm
scatterbrained from trying to too juggle too many things these last few
weeks!

-Jason

**Comment by joshuamcginnis** [comment]
The url is in the api2 xml response (same link referenced in the first post from this thread). Images currently look like so:

```xml
<images number=5>
  <image id="1278764" type="image">
  <date type="date" format="YYYY-MM-DD">2020-11-13</date>
  <license type="string" content_type="text/plain">Creative Commons Wikipedia Compatible v3.0</license>
  <quality type="float" range="-3.0 to 3.0">4.0</quality>
</images>
```

Suggest adding `url` as either an attribute on `<image>` or by giving it it's own node.

Thanks for responding so quickly!

**Comment by pellaea** [comment]
Ah yes, got it.  Okay, I'm adding "original_url" as a new node under
<image>.  I'll push it out in a bit, just waiting for tests to pass and all
that.

**Comment by joshuamcginnis** [comment]
Cool. What does the original part refer to? Are there other kinds of image urls?

**Comment by pellaea** [comment]
Yeah, we keep multiple copies of each image: the original, and several
down-scaled copies: 1280, 960, 640, 320 and "thumb".  1280, for example, is
scaled down to fit within a 1280x1280 pixel box, and so on.

**Comment by joshuamcginnis** [comment]
Ah, cool. That's perfect. 👌

**Comment by pellaea** [comment]
For what it's worth, you can create the image URL yourself with just the ID:

https://mushroomobserver.org/images/$size/$id.jpg

That will redirect to wherever the image is currently being served from.
That URL is guaranteed for as long as MO is around.

$size is one of: "orig", 1280, 960, 640, 320, "thumb"

**Comment by joshuamcginnis** [comment]
Yea, I'm trying to help get the iNat MushroomObserver importer working again and right now, it's hardcoding MO urls and one of them is an old-format image url that no longer works. You fixing this is going to make it so that if you decide to change your url schema, clients like iNat don't have to make any updates (in most cases).

**Comment by pellaea** [comment]
All good now.  Give it a spin, see if that works for you guys.  Thanks for
reaching out!  I'd much rather fix bugs on our side than have clients do
work-arounds. :)

**Comment by joshuamcginnis** [comment]
Looks good so far! I'll confirm later if everything seems fine from the other codebase. Thanks again.
