### ISSUE TITLE
Wild Cube from Arkansas' fertile river valley!

### ISSUE THREAD

**Issue by Jococube** [MushroomObserver/mushroom-observer#827]
As soon as I picked this specimen I brought it home and cloned and printed it seeing that it was the most beautiful cube I've seen. Due to the gold contrast and the fact that it was discovered in a pasture parallel with the Arkansas River I'm calling this new variety Golden River! This was discovered in Ozark, AR. Mush love 🙏🍄💙
![IMG_20211101_174441_5](https://user-images.githubusercontent.com/98142791/150470323-71f4aee8-f8f5-488e-86cb-a990c323c40d.jpg)
![IMG_20211101_174452_3](https://user-images.githubusercontent.com/98142791/150470325-a5c962a6-ff47-40da-a960-93a310e3187e.jpg)
![IMG_20211101_174530_0-1 (1)](https://user-images.githubusercontent.com/98142791/150470326-f5dfe253-30e6-443c-8b2c-ebf3c133e7bf.jpg)
![IMG_20211101_174456_2](https://user-images.githubusercontent.com/98142791/150470364-cae80d40-a45e-4fd7-9d76-9376086d7386.jpg)
![IMG_20211215_135008_313](https://user-images.githubusercontent.com/98142791/150470365-73b702cd-421e-4f90-8f15-78e00616bb94.jpg)
![IMG_20211215_135008_108](https://user-images.githubusercontent.com/98142791/150470369-ae384392-e806-45c1-86a3-de61dfca53dc.jpg)
![IMG_20211215_135008_241](https://user-images.githubusercontent.com/98142791/150470370-a45e1043-9053-4781-b742-b8c72a30f1a2.jpg)

**Comment by JoeCohen** [comment]
@Jococube: 
- Please review the documentation about both GitHub and GitHub issues before attempting any further use of GitHub. 
- This "Issue" is an abuse of both. It has been labeled "spam" and "invalid", and will be closed. In addition, you have been blocked.
